version: 1
builder:
  configs:
    - platform: ios
      scheme: Period
    - platform: macos-xcodebuild
      scheme: Period
    - platform: tvos
      scheme: Period
    - platform: watchos
      scheme: Period
